-- Run this script in your Oracle schema (SQL*Plus, SQL Developer, etc.)
-- before using the Register button.

CREATE TABLE registered_users (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR2(120) NOT NULL,
    email         VARCHAR2(120) NOT NULL,
    phone_num     VARCHAR2(40),
    address_line  VARCHAR2(300),
    pwd           VARCHAR2(200) NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_registered_users_email ON registered_users (email);
